[package]
name = "wcalc"
version = "1.0.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_6"] }
meval = "0.2.0"
regex = "1.10.6"
sysinfo = "0.32.0"
